### ISSUE TITLE
Can't compile in 2023

### ISSUE THREAD

**Issue by PeteHaughie** [sansculotte/pd-zmq#2]
I realise that this is an old project but I really need to use zmq in a large distributed PD implementation. I have access to the darwin build but not one that will work on M1/M2 ARM64 architecture.

When I run the makefile I get a bunch of errors:
```
warning: optimization level '-O6' is not supported; using '-O3' instead
zmq.c:166:7: error: call to undeclared function 'error'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      error("invalid socket type or not yet implemented");
      ^
zmq.c:188:7: error: call to undeclared function 'error'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      error("create a socket first");
      ^
zmq.c:229:7: error: call to undeclared function 'error'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      error("create and connect socket before sending anything");
      ^
zmq.c:246:7: error: call to undeclared function 'error'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      error("create a socket first");
      ^
zmq.c:250:7: error: call to undeclared function 'error'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      error("socket already in use");
      ^
zmq.c:265:7: error: call to undeclared function 'error'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      error("no socket");
      ^
zmq.c:269:7: error: call to undeclared function 'error'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      error("socket not bound");
      ^
zmq.c:285:7: error: call to undeclared function 'error'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      error("create socket first");
      ^
zmq.c:289:7: error: call to undeclared function 'error'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      error("socket already in use");
      ^
zmq.c:304:7: error: call to undeclared function 'error'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      error("no socket");
      ^
zmq.c:308:7: error: call to undeclared function 'error'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      error("socket not connected");
      ^
```
Any help you could offer would be greatly appreciated

**Comment by sansculotte** [comment]
@PeteHaughie
Right. I'm getting these too. the error function does apparently not exist anymore, but there is the pd_error function instead, so i have replaced all instances of error with pd_error and pushed that to the master branch.

The build is tripping over a new error however:
`zmq.c: In function ‘zmq_setup’:
zmq.c:478:10: error: cast between incompatible function types from ‘void * (*)(t_symbol *, int,  t_atom *)’ {aka ‘void * (*)(struct _symbol *, int,  struct _atom *)’} to ‘void * (*)(void)’ [-Werror=cast-function-type]
  478 |          (t_newmethod)zmq_new,
      |          ^`

**Comment by sansculotte** [comment]
I am able to bypass the error by compiling without the -WError option and the resulting external does load in pd and not crash on errors. will need some time to sort that out and even upload an M1 built to deken.

**Comment by PeteHaughie** [comment]
Great start!

**Comment by sansculotte** [comment]
I am able to bypass the error by compiling without the -WError option and the resulting external does load in pd and not crash on errors. will need some time to sort that out and even upload an M1 built to deken.

**Comment by sansculotte** [comment]
pushed the Makefile with disabled function type warning. pd-zmq should build without errors now.
